/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BCH_Decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cb26ad2ad10c8cfa4c8f947bb8313882)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ITpp/BCH_Decoder.h>
// pydoc.h is automatically generated in the build directory
#include <BCH_Decoder_pydoc.h>

void bind_BCH_Decoder(py::module& m)
{

    using BCH_Decoder    = gr::ITpp::BCH_Decoder;


    py::class_<BCH_Decoder, gr::block, gr::basic_block,
        std::shared_ptr<BCH_Decoder>>(m, "BCH_Decoder", D(BCH_Decoder))

        .def(py::init(&BCH_Decoder::make),
           D(BCH_Decoder,make)
        )
        



        ;




}








