/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BCH_Encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(964967c2582311d5177a952664730534)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ITpp/BCH_Encoder.h>
// pydoc.h is automatically generated in the build directory
#include <BCH_Encoder_pydoc.h>

void bind_BCH_Encoder(py::module& m)
{

    using BCH_Encoder    = gr::ITpp::BCH_Encoder;


    py::class_<BCH_Encoder, gr::block, gr::basic_block,
        std::shared_ptr<BCH_Encoder>>(m, "BCH_Encoder", D(BCH_Encoder))

        .def(py::init(&BCH_Encoder::make),
           D(BCH_Encoder,make)
        )
        



        ;




}








