/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BER_Analyzer_cpp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(73038cba9168f1477fe456f074f13a3e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ITpp/BER_Analyzer_cpp.h>
// pydoc.h is automatically generated in the build directory
#include <BER_Analyzer_cpp_pydoc.h>

void bind_BER_Analyzer_cpp(py::module& m)
{

    using BER_Analyzer_cpp    = gr::ITpp::BER_Analyzer_cpp;


    py::class_<BER_Analyzer_cpp, gr::block, gr::basic_block,
        std::shared_ptr<BER_Analyzer_cpp>>(m, "BER_Analyzer_cpp", D(BER_Analyzer_cpp))

        .def(py::init(&BER_Analyzer_cpp::make),
           D(BER_Analyzer_cpp,make)
        )
        



        ;




}








