/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Decoder_BPSK.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4abc2a1e9dca96da9373d42f07914aab)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ITpp/Decoder_BPSK.h>
// pydoc.h is automatically generated in the build directory
#include <Decoder_BPSK_pydoc.h>

void bind_Decoder_BPSK(py::module& m)
{

    using Decoder_BPSK    = ::gr::ITpp::Decoder_BPSK;


    py::class_<Decoder_BPSK, gr::block, gr::basic_block,
        std::shared_ptr<Decoder_BPSK>>(m, "Decoder_BPSK", D(Decoder_BPSK))

        .def(py::init(&Decoder_BPSK::make),
           py::arg("m"),
           D(Decoder_BPSK,make)
        )
        



        ;




}








