/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Hamming_Decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(85b5ace0d4ade24786d3f5057e59e4c5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ITpp/Hamming_Decoder.h>
// pydoc.h is automatically generated in the build directory
#include <Hamming_Decoder_pydoc.h>

void bind_Hamming_Decoder(py::module& m)
{

    using Hamming_Decoder    = gr::ITpp::Hamming_Decoder;


    py::class_<Hamming_Decoder, gr::block, gr::basic_block,
        std::shared_ptr<Hamming_Decoder>>(m, "Hamming_Decoder", D(Hamming_Decoder))

        .def(py::init(&Hamming_Decoder::make),
           D(Hamming_Decoder,make)
        )
        



        ;




}








