/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Hamming_Encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(db786f9d3cae6aa82c987353d15edbfb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ITpp/Hamming_Encoder.h>
// pydoc.h is automatically generated in the build directory
#include <Hamming_Encoder_pydoc.h>

void bind_Hamming_Encoder(py::module& m)
{

    using Hamming_Encoder    = gr::ITpp::Hamming_Encoder;


    py::class_<Hamming_Encoder, gr::block, gr::basic_block,
        std::shared_ptr<Hamming_Encoder>>(m, "Hamming_Encoder", D(Hamming_Encoder))

        .def(py::init(&Hamming_Encoder::make),
           D(Hamming_Encoder,make)
        )
        



        ;




}








