/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(RS_Decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cb79a4b720054015b2e7fc6a6d8af5ff)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ITpp/RS_Decoder.h>
// pydoc.h is automatically generated in the build directory
#include <RS_Decoder_pydoc.h>

void bind_RS_Decoder(py::module& m)
{

    using RS_Decoder    = gr::ITpp::RS_Decoder;


    py::class_<RS_Decoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<RS_Decoder>>(m, "RS_Decoder", D(RS_Decoder))

        .def(py::init(&RS_Decoder::make),
           D(RS_Decoder,make)
        )
        



        ;




}








