/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(RS_Encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(beae9c4ca22c00158ef307b6fd8b0ccd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ITpp/RS_Encoder.h>
// pydoc.h is automatically generated in the build directory
#include <RS_Encoder_pydoc.h>

void bind_RS_Encoder(py::module& m)
{

    using RS_Encoder    = gr::ITpp::RS_Encoder;


    py::class_<RS_Encoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<RS_Encoder>>(m, "RS_Encoder", D(RS_Encoder))

        .def(py::init(&RS_Encoder::make),
           D(RS_Encoder,make)
        )
        



        ;




}








