/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ITpp
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_ITPP_API_H
#define INCLUDED_ITPP_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ITpp_EXPORTS
#define ITPP_API __GR_ATTR_EXPORT
#else
#define ITPP_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_ITPP_API_H */
